name: CI

on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm i

      - name: npm install jest
        run: npm i jest

      - name: npm install supertest
        run: npm i supertest

      - name: npm test
        run: npm run test --forceExit --noStackTrace
